test

diff --git a/.github/workflows/second.yml b/.github/workflows/second.yml
--- a/.github/workflows/second.yml
+++ b/.github/workflows/second.yml
@@ -55,18 +55,17 @@ jobs:
           git checkout -b preproduction 
           git checkout -b tmp-sync 
 
-          echo "Content of include.txt:"
-          cat -A .github/include.txt  
-
           #remove all files except .git
           find . -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} + 
 
           #checkout files/directories listed in include.txt
           while IFS= read -r path; do 
+            normalized_path = "$(echo -e "${path}") | sed 's/^M$//g' $path"
             echo "checking include_path: $path"
-            if [[ -n $path && ! $path =~ ^[[:space:]]*# ]]; then 
+            echo "checking normalized_path: $normalized_path"
+            if [[ -n $normalized_path && ! $normalized_path =~ ^[[:space:]]*# ]]; then 
               echo "match found."
-              git checkout main -- "$path"* || echo "WARNING: Failed to checkout $path"
+              git checkout main -- $normalized_path* || echo "WARNING: Failed to checkout $path"
             fi 
 
           done <<< "$INCLUDE_PATHS"
