test

diff --git a/.github/workflows/second.yml b/.github/workflows/second.yml
--- a/.github/workflows/second.yml
+++ b/.github/workflows/second.yml
@@ -63,7 +63,7 @@ jobs:
             echo "checking include_path: $path"
             if [[ -n $path && ! $path =~ ^[[:space:]]*# ]]; then 
               echo "match found."
-              git checkout main -- "$path" || echo "WARNING: Failed to checkout $path"
+              git checkout main -- "$path"* || echo "WARNING: Failed to checkout $path"
             fi 
 
           done <<< "$INCLUDE_PATHS"
